### ISSUE TITLE
RemoteApplications does not work with RF 2.6

### ISSUE THREAD

**Issue by GoogleCodeExporter** [narendrabtechcse/robotframework-javatools#56]
```
Due to refactorings in the robot/running/importer.py file to Importer and 
ImportCache, RemoteApplications does not work with RF 2.6. 

It fails with the error that "_libraries" is not a member of IMPORTER.

I attach a solution, however, it is not backwards compatible with earlier 
versions of RF.

```

Original issue reported on code.google.com by `robinsthom` on 28 Jul 2011 at 2:33

Attachments:
- [RemoteApplications-2.6.patch](https://storage.googleapis.com/google-code-attachments/robotframework-javatools/issue-56/comment-0/RemoteApplications-2.6.patch)
